version: "3.6"

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017

  storage:
    image: minio/minio
    hostname: "storage"
    environment:
      MINIO_ACCESS_KEY: "YourMinioAccessKey"
      MINIO_SECRET_KEY: "YourMinioSecret"
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data
    ports:
      - 9000:9000

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://storage:9000 YourMinioAccessKey YourMinioSecret;
      /usr/bin/mc rm -r --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
  director:
    image: stefanso/sorry-cypress-director:latest
    links:
      - "storage:storage"
    environment:
      DASHBOARD_URL: http://localhost:8080
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "sorry-cypress"
      EXECUTION_DRIVER: "../execution/mongo/driver"
      SCREENSHOTS_DRIVER: "../screenshots/minio.driver"
      AWS_ACCESS_KEY_ID: "key"
      AWS_SECRET_ACCESS_KEY: "secret"
      S3_BUCKET: sorry-cypress
      MINIO_ACCESS_KEY: "YourMinioAccessKey"
      MINIO_SECRET_KEY: "YourMinioSecret"
      MINIO_ENDPOINT: "storage"
      MINIO_URL: "http://storage"
      MINIO_PORT: "9000"
      MINIO_USESSL: "false"
      MINIO_BUCKET: sorry-cypress
    ports:
      - 1234:1234
    depends_on:
      - mongo
      - storage
  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "sorry-cypress"
    ports:
      - 4000:4000
    depends_on:
      - mongo
  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api
